version: '3.1'

services:
    db:
        image: mysql:5
        ports:
            - 3306:3306
        volumes: 
            -  ../db:/var/lib/mysql
        env_file: 
            - ./.env.dev
            
    web:
        build:
            context: ../src
            dockerfile: ../docker/Dockerfile
        command: bash -c "python manage.py migrate && django-admin compilemessages && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ../src:/code
            - ../media_volume:/code/mediafiles
        ports:
            - 8000:8000
        env_file: 
            - ./.env.dev
        depends_on: 
            - db

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on: 
            - db