version: '3.1'

services:
    db:
        image: mysql:5
        ports:
            - 3306:3306
        volumes: 
            -  ../db:/var/lib/mysql
        env_file: 
            - ./.env.prod.db
        environment: 
            MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${SQL_DATABASE}
            MYSQL_USER: ${SQL_USER}
            MYSQL_PASSWORD: ${SQL_PASSWORD} 
            
    web:
        build:
            context: ../src
            dockerfile: ../docker/Dockerfile.prod
        command: gunicorn cc_project.wsgi:application --bind 0.0.0.0:8000
        expose:
            - 8000
        env_file: 
            - ./.env.prod
        depends_on: 
            - db
        volumes:
            - ../static_volume:/code/staticfiles
            - ../media_volume:/code/mediafiles

    nginx:
        build: ../nginx
        ports:
            - 1337:80
        depends_on: 
            - web
        volumes:
            - ../static_volume:/code/staticfiles
            - ../media_volume:/code/mediafiles

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on: 
            - db

