version: '3.1'

services:
    db:
        image: mysql:5
        ports:
            - 3306:3306
        volumes: 
            -  ../db:/var/lib/mysql
        env_file: 
            - ./.env.prod.db

    web:
        build:
            context: ../src
            dockerfile: ../docker/Dockerfile.prod
        command: bash -c "python manage.py migrate && django-admin compilemessages && python manage.py collectstatic --noinput && gunicorn cc_project.wsgi:application --bind 0.0.0.0:8000"
        expose:
            - 8000
        env_file: 
            - ./.env.prod
        depends_on: 
            - db
        volumes:
            - ../static_volume:/code/staticfiles
            - ../media_volume:/code/mediafiles

    nginx:
        build: ../nginx
        ports:
            - 80:80
            - 443:443
        depends_on: 
            - web
        volumes:
            - ../static_volume:/code/staticfiles
            - ../media_volume:/code/mediafiles
            - ../nginx/certs:/etc/nginx/certs
