# Generated by Django 3.0.9 on 2020-08-24 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ingredients', models.TextField(null=True)),
                ('allergens', models.TextField(null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='ciasta_ciasteczka.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('diameter', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.FloatField(null=True)),
                ('amount_of_people', models.IntegerField()),
                ('tray', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.Tray')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('altr_text', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.Product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='ciasta_ciasteczka.Size'),
        ),
    ]
