# Generated by Django 3.0.10 on 2020-09-27 18:38

import ciasta_ciasteczka.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ciasta_ciasteczka', '0001_initial'), ('ciasta_ciasteczka', '0002_auto_20200826_1956'), ('ciasta_ciasteczka', '0003_auto_20200826_1958'), ('ciasta_ciasteczka', '0004_auto_20200826_2035'), ('ciasta_ciasteczka', '0005_auto_20200826_2207'), ('ciasta_ciasteczka', '0006_auto_20200826_2213'), ('ciasta_ciasteczka', '0007_auto_20200827_1841'), ('ciasta_ciasteczka', '0008_slideshowphoto'), ('ciasta_ciasteczka', '0009_auto_20200830_2020'), ('ciasta_ciasteczka', '0010_product_creation_date'), ('ciasta_ciasteczka', '0011_auto_20200830_2111'), ('ciasta_ciasteczka', '0012_auto_20200830_2112'), ('ciasta_ciasteczka', '0013_auto_20200831_1955'), ('ciasta_ciasteczka', '0014_auto_20200831_1957'), ('ciasta_ciasteczka', '0015_auto_20200831_1959'), ('ciasta_ciasteczka', '0016_auto_20200901_1444'), ('ciasta_ciasteczka', '0017_remove_productphoto_name'), ('ciasta_ciasteczka', '0018_auto_20200902_1711'), ('ciasta_ciasteczka', '0019_auto_20200908_1105'), ('ciasta_ciasteczka', '0020_auto_20200915_1858'), ('ciasta_ciasteczka', '0021_product_modified'), ('ciasta_ciasteczka', '0022_auto_20200926_1649'), ('ciasta_ciasteczka', '0023_auto_20200927_2038')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.Category', verbose_name='parent category')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('diameter', models.IntegerField(blank=True, null=True, verbose_name='diameter')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='width')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='length')),
                ('max_amount_of_people', models.IntegerField(default=0, verbose_name='maximum amount of people')),
                ('min_amount_of_people', models.IntegerField(default=0, verbose_name='minimum amount of people')),
            ],
            options={
                'verbose_name': 'tray',
                'verbose_name_plural': 'trays',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='weight')),
                ('tray', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.Tray', verbose_name='tray')),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price_unit', models.CharField(max_length=10, verbose_name='price unit')),
            ],
            options={
                'verbose_name': 'product type',
                'verbose_name_plural': 'product types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('hidden', models.BooleanField(default=False, verbose_name='hidden')),
                ('category', models.ManyToManyField(to='ciasta_ciasteczka.Category', verbose_name='category')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('product_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.ProductType', verbose_name='type')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=100, verbose_name='alternative text')),
                ('photo', models.ImageField(upload_to=ciasta_ciasteczka.utils.RandomFileName('products/'), verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.Product', verbose_name='product')),
                ('main', models.BooleanField(default=False, verbose_name='main photo')),
            ],
            options={
                'verbose_name': 'product photo',
                'verbose_name_plural': 'product photos',
            },
        ),
        migrations.CreateModel(
            name='SizeProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.Product', verbose_name='product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.Size', verbose_name='size')),
            ],
            options={
                'verbose_name': 'size and price of product',
                'verbose_name_plural': 'sizes and prices of products',
            },
        ),
        migrations.CreateModel(
            name='SlideshowPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='text')),
                ('image', models.ImageField(upload_to=ciasta_ciasteczka.utils.RandomFileName('slideshow/'))),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='alternative text')),
                ('hidden', models.BooleanField(default=False, verbose_name='hidden')),
            ],
            options={
                'verbose_name': 'slideshow photot',
                'verbose_name_plural': 'slideshow photos',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('allergen', models.BooleanField(default=False, verbose_name='allergen')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='ciasta_ciasteczka.Ingredient', verbose_name='ingredients'),
        ),
    ]
