# Generated by Django 3.0.9 on 2020-08-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0002_auto_20200826_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allergens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='tray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.Tray'),
        ),
        migrations.AlterField(
            model_name='size',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
