# Generated by Django 3.0.10 on 2020-09-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0003_auto_20200930_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='priority',
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=1, verbose_name='priority'),
        ),
    ]
