# Generated by Django 3.0.9 on 2020-08-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0003_auto_20200826_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.Product', verbose_name='Product'),
        ),
    ]
