# Generated by Django 3.0.9 on 2020-08-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0005_auto_20200826_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
