# Generated by Django 3.0.9 on 2020-08-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0006_auto_20200826_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Main photo'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
