# Generated by Django 3.0.9 on 2020-08-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0008_slideshowphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productphoto',
            old_name='altr_text',
            new_name='alt_text',
        ),
        migrations.RenameField(
            model_name='slideshowphoto',
            old_name='altr_text',
            new_name='alt_text',
        ),
    ]
