# Generated by Django 3.0.9 on 2020-08-30 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0009_auto_20200830_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 18, 28, 51, 478498, tzinfo=utc)),
        ),
    ]
