# Generated by Django 3.0.9 on 2020-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0012_auto_20200830_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='amount_of_people',
        ),
        migrations.AddField(
            model_name='size',
            name='max_amount_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='size',
            name='min_amount_of_people',
            field=models.IntegerField(default=0),
        ),
    ]
