# Generated by Django 3.0.9 on 2020-08-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0013_auto_20200831_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tray',
            name='diameter',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tray',
            name='length',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tray',
            name='width',
            field=models.IntegerField(blank=True),
        ),
    ]
