# Generated by Django 3.0.9 on 2020-09-01 12:44

import ciasta_ciasteczka.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0015_auto_20200831_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='max_amount_of_people',
        ),
        migrations.RemoveField(
            model_name='size',
            name='min_amount_of_people',
        ),
        migrations.AddField(
            model_name='tray',
            name='max_amount_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tray',
            name='min_amount_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='alt_text',
            field=models.CharField(max_length=100, verbose_name='Alternative text'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(upload_to=ciasta_ciasteczka.utils.RandomFileName('products/')),
        ),
        migrations.AlterField(
            model_name='size',
            name='tray',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciasta_ciasteczka.Tray'),
        ),
    ]
