# Generated by Django 3.0.9 on 2020-09-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0016_auto_20200901_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='name',
        ),
    ]
