# Generated by Django 3.0.9 on 2020-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0017_remove_productphoto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
