# Generated by Django 3.0.9 on 2020-09-08 09:05

import ciasta_ciasteczka.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0018_auto_20200902_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshowphoto',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slideshowphoto',
            name='image',
            field=models.ImageField(upload_to=ciasta_ciasteczka.utils.RandomFileName('slideshow/')),
        ),
    ]
