# Generated by Django 3.0.10 on 2020-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciasta_ciasteczka', '0022_auto_20200926_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='ciasta_ciasteczka.Ingredient', verbose_name='ingredients'),
        ),
    ]
